# Generated by Django 5.2.1 on 2025-06-11 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_posted_at_job_skills_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 18, 13, 56, 58, 965442, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='job',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='open', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills_required',
            field=models.CharField(default='general', max_length=200),
            preserve_default=False,
        ),
    ]
