# Generated by Django 5.2.1 on 2025-06-12 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_expiry_date_job_is_urgent_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 7, 56, 28, 371642, tzinfo=datetime.timezone.utc)),
        ),
    ]
