# Generated by Django 5.2.1 on 2025-06-12 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget',
           field=models.DecimalField(default=0, max_digits=10, decimal_places=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 7, 57, 13, 564515, tzinfo=datetime.timezone.utc)),
        ),
    ]
