# Generated by Django 5.2.1 on 2025-06-12 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_budget_job_is_negotiable_alter_job_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 8, 1, 13, 135315, tzinfo=datetime.timezone.utc)),
        ),
    ]
