# Generated by Django 5.2.1 on 2025-06-12 08:55

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_budget_alter_job_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 19, 8, 55, 49, 159640, tzinfo=datetime.timezone.utc)),
        ),
    ]
